export const SET_RANDOM_FIRST_GROUND_BALATA = "SET_RANDOM_FIRST_GROUND_BALATA";
export const SET_RANDOM_INITIAL_BALATAS_FOR_PLAYERS =
  "SET_RANDOM_INITIAL_BALATAS_FOR_PLAYERS";
export const SET_FIRST_GROUND_BALATA = "SET_FIRST_GROUND_BALATA";
export const SET_LAST_GROUND_BALATA = "SET_LAST_GROUND_BALATA";
export const SET_DRAGGED_BALATA = "SET_DRAGGED_BALATA";
export const ON_DRAGGED_BALATA_RELEASE = "ON_DRAGGED_BALATA_RELEASE";
