export const SET_RANDOM_FIRST_GROUND_BALATA = "SET_RANDOM_FIRST_GROUND_BALATA";
export const SET_RANDOM_INITIAL_BALATAS_FOR_PLAYERS =
  "SET_RANDOM_INITIAL_BALATAS_FOR_PLAYERS";
export const ON_BALATA_CHOSEN = "ON_BALATA_CHOSEN";
export const ON_SPARE_BALATA_CHOSEN = "ON_SPARE_BALATA_CHOSEN";
export const TOGGLE_SPARE_BALATAS = "TOGGLE_SPARE_BALATAS";
export const ON_DECIDE_OPPONENT = "ON_DECIDE_OPPONENT";
export const SET_WINNER = "SET_WINNER";
export const RESET_GAME_AND_PLAY = "RESET_GAME_AND_PLAY";
